### ISSUE TITLE
提几个需求

### ISSUE THREAD

**Issue by mengnimen** [BapiGso/gopanel#8]
大佬 我来提需求了
1、啥时候能有中文（虽然就几个单词能看懂，但是还是希望能有中文）
2、希望有一个重启选项，要不每次都得连SSH后再执行。
3、改密码之后能不能提示重启，点击之后自动重启
4、能不能有自动更新选项😂
5、配置文件能不能和程序在一个目录或者指定目录
6、能不能把frpc也加上，这样我就可以不用安装frpc了，直接使用。
另外那个cron定时，是不是可以定期运行，保号sevr00.com，要求3个月登录一次SSH
再次感谢，N1盒子跑这个非常方便，如果安装能做成一键脚本就更完美了（虽然现在安装也是复制粘贴即可）

**Comment by BapiGso** [comment]
1-5都很好加，因为之前用的人少没考虑这么多，6的话要看看frpc源代码

**Comment by BapiGso** [comment]
是的cron就是执行你输入的命令，你输入一个连接本地ssh的命令就行

**Comment by mengnimen** [comment]
> 1-5都很好加，因为之前用的人少没考虑这么多，6的话要看看frpc源代码

嗯嗯，多谢

**Comment by BapiGso** [comment]
Complete #8

This issue was completed by commit 50f020a0d66e731daff470381c58eac4dae9e7f1.
