### ISSUE TITLE
一键访问问题

### ISSUE THREAD

**Issue by mengnimen** [BapiGso/gopanel#9]
大佬，还有一个问题，就是国内访问的问题，你的一键，访问不了，加个代理最好了

**Comment by mengnimen** [comment]
刚更新完
在点击重启后没提示，不知道重启后是否成功
不知道重启后还需要不需要再打开frpc，最好是可以自动重启。这样就不会失联了

**Comment by BapiGso** [comment]
一键访问只能用户自己解决，我没有办法找到一个可信且稳定持久的代理
现在新增了重启loading动画了，caddy、frp的重启可以通过点击enable按钮来设置是否跟随面板一起启动
